# OBS SPACE OF SIZE 5
# Observation vector ###  Y   Z   R   VY  VZ
# Hover to a point

# --- Environment options ---
env:
  env_id: "hover-env-v0" # Environment name
  env_kwargs:
    drone_model: "SINGLE_TEST_DRONE" # Drone model
    initial_xyzs: None # Initial position
    initial_rpys: None # Initial orientation
    sim_freq: 100 # Simulation frequency
    ctrl_freq: 100 # Control frequency
    obs: "KIN_REL" # Observation type
    act: "RATE" # Action type
    dim: "DIM_2" # Simulation dimension
    episode_len_sec: 15 # Episode length in seconds
    eval_mode: False # Evaluation mode
    sensor_sigma: 0 # Sensor noise
    domain_rand: False # Domain randomization