# --- Environment options ---
env:
  env_id: "race-env-v0" # Environment name
  env_kwargs:
    drone_model: "MULTI_TEST_DRONE" # Drone model
    num_drones: 3 # Number of drones in the environment
    initial_xyzs: None # Initial position
    initial_rpys: None # Initial orientation
    sim_freq: 100 # Simulation frequency
    ctrl_freq: 100 # Control frequency
    obs: "RACE_MULTI" # Observation type
    act: "RATE" # Action type
    dim: "DIM_3" # Simulation dimension
    episode_len_sec: 15 # Episode length in seconds
    use_mappo: True # Use MAPPO algorithm
    eval_mode: False # Evaluation mode
    sensor_sigma: 0 # Sensor noise
    domain_rand: False # Domain randomization
    alert_dist: 0.3 # Alert distance for drones, 3R, R = 0.16
    collision_radius: 0.2 # Collision radius for drones, 2R, R = 0.16
  monitor_kwargs:
    use_share_obs_env: True # Use shared observations for environment type